version: '3.8'

services:

  app:
    build: .
    container_name: app
    networks:
      - backend
    depends_on:
      - db_master
      - db_test
    stdin_open: true
    tty: true
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost" ]

  db_master:
    image: 'postgres:latest'
    container_name: db_master
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: director
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: university
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - db_master:/var/lib/postgresql/data

  db_test:
    image: 'postgres:latest'
    container_name: db_test
    ports:
      - "5050:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: university
    deploy:
      restart_policy:
        condition: on-failure

networks:
  backend:

volumes:
  db_master: {}